export default {
  parser: 'babel-eslint',
  parserOptions: {
    ecmaFeatures: {
      jsx: true,
    },
  },
  extends: [
    'esnext',
    'plugin:import/recommended',
    'plugin:promise/recommended',
  ],
  env: {
    es6: true,
  },
  plugins: [
    'babel',
    'import',
    'sort-destructure-keys',
  ],
  rules: {
    'array-bracket-spacing': ['error', 'never'],
    'block-spacing': 'error',
    'comma-dangle': ['error', 'always-multiline'],
    'computed-property-spacing': ['error', 'never'],
    'function-paren-newline': ['error', 'consistent'],
    'import/no-namespace': 'off',
    'import/prefer-default-export': 'off',
    'no-console': 'error',
    'no-invalid-this': 'off',
    'babel/no-invalid-this': 'error',
    'no-multi-spaces': 'error',
    'no-spaced-func': 'error',
    'no-trailing-spaces': 'error',
    'object-curly-newline': ['error', { consistent: true }],
    'object-property-newline': ['error', { allowAllPropertiesOnSameLine: true }],
    'operator-linebreak': ['error', 'before'],
    'padded-blocks': ['error', 'never'],
    'padding-line-between-statements': [
      'error',
      { blankLine: 'always', prev: ['const', 'let', 'var'], next: '*' },
      { blankLine: 'any', prev: ['const', 'let', 'var'], next: ['const', 'let', 'var'] },
    ],
    quotes: ['error', 'single'],
    'quote-props': ['error', 'as-needed', { numbers: true }],
    semi: ['error', 'never'],
    'sort-destructure-keys/sort-destructure-keys': 'error',
    'space-before-blocks': 'error',
    'space-in-parens': ['error', 'never'],
    'space-unary-ops': 'error',
  },
}
